name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - uses: astral-sh/uv-action@v1
      - name: Install dependencies
        run: uv sync --dev
      - name: Run pre-commit
        run: uv run pre-commit run --all-files
